language: rust
dist: bionic
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_install:
  - set -e
  - rustup component add rustfmt
  - rustup component add clippy
  - sudo apt-get install -y libgdal-dev
script:
  - cargo build
  - cargo test
  - cargo fmt -- --check
  - cargo clean
  - cargo clippy --all -- -D warnings
